#!/bin/sh

rsvg-convert -o search.png _source/search.svg
rsvg-convert -o all-tags.png _source/all-tags.svg
rsvg-convert -o bell.png _source/bell.svg
rsvg-convert -o bell2.png _source/bell2.svg
rsvg-convert -o pinned.png _source/pinned.svg
rsvg-convert -o go-last.png _source/go-last.svg
rsvg-convert -o go-unread.png _source/go-unread.svg
rsvg-convert -o mark-read.png _source/mark-read.svg
rsvg-convert -o rss.png _source/rss.svg
rsvg-convert -o edit.png _source/edit.svg
rsvg-convert -o quote.png _source/quote.svg
rsvg-convert -o del.png _source/del.svg
rsvg-convert -o history.png _source/history.svg
